#####
# This file defines the builds that will be executed by the CI
#####

- name: ubuntu-desktop
  template: linux-desktop
  var-files: common,kvm,linux,ubuntu-focal
  path-filters: |
    paths:
      - .github/workflows/pr.yml
      - bin/*
      - config.pkr.hcl
      - requirements.yml
      - env/*/common.env
      - env/*/kvm.env
      - env/*/linux.env
      - env/*/ubuntu-focal.env
      - vars/*/common.json
      - vars/*/kvm.json
      - vars/*/linux.json
      - vars/*/ubuntu-focal.json
      - packer/linux-desktop.pkr.hcl
      - ansible/linux-webconsole.yml
      - ansible/roles/linux-webconsole/**
      - ansible/roles/linux-ansible-init/**
      - ansible/roles/linux-podman/**
      - ansible/roles/linux-data-volumes/**
      - ansible/roles/linux-guacamole/**
      - ansible/roles/linux-monitoring/**
      - ansible/roles/linux-zenith-client/**

- name: ubuntu-rdp-gateway
  template: linux-rdp-gateway
  var-files: common,kvm,linux,ubuntu-focal
  path-filters: |
    paths:
      - .github/workflows/pr.yml
      - bin/*
      - config.pkr.hcl
      - requirements.yml
      - env/*/common.env
      - env/*/kvm.env
      - env/*/linux.env
      - env/*/ubuntu-focal.env
      - vars/*/common.json
      - vars/*/kvm.json
      - vars/*/linux.json
      - vars/*/ubuntu-focal.json
      - packer/linux-rdp-gateway.pkr.hcl
      - ansible/linux-rdp-gateway.yml
      - ansible/roles/linux-rdp-gateway/**
      - ansible/roles/linux-ansible-init/**
      - ansible/roles/linux-podman/**
      - ansible/roles/linux-data-volumes/**
      - ansible/roles/linux-guacamole/**
      - ansible/roles/linux-zenith-client/**

- name: jupyter-repo2docker
  template: jupyter-repo2docker
  var-files: common,kvm,linux,ubuntu-focal
  path-filters: |
    paths:
      - .github/workflows/pr.yml
      - bin/*
      - config.pkr.hcl
      - requirements.yml
      - env/*/common.env
      - env/*/kvm.env
      - env/*/linux.env
      - env/*/ubuntu-focal.env
      - vars/*/common.json
      - vars/*/kvm.json
      - vars/*/linux.json
      - vars/*/ubuntu-focal.json
      - packer/jupyter-repo2docker.pkr.hcl
      - ansible/jupyter-repo2docker.yml
      - ansible/roles/jupyter-repo2docker/**
      - ansible/roles/linux-ansible-init/**
      - ansible/roles/linux-podman/**
      - ansible/roles/linux-data-volumes/**
      - ansible/roles/linux-monitoring/**
      - ansible/roles/linux-zenith-client/**

# For now, we build Kubernetes images for focal _and_ jammy
- name: kubernetes-1-25-focal
  template: kubernetes
  var-files: common,kvm,linux,ubuntu-focal,kubernetes,kubernetes_1_25
  path-filters: |
    paths:
      - .github/workflows/pr.yml
      - bin/*
      - config.pkr.hcl
      - requirements.yml
      - env/*/common.env
      - env/*/kvm.env
      - env/*/linux.env
      - env/*/ubuntu-focal.env
      - env/*/kubernetes.env
      - env/*/kubernetes_1_25.env
      - vars/*/common.json
      - vars/*/kvm.json
      - vars/*/linux.json
      - vars/*/ubuntu-focal.json
      - vars/*/kubernetes.json
      - vars/*/kubernetes_1_25.json
      - packer/kubernetes.pkr.hcl
      - vendor/image-builder/**

- name: kubernetes-1-25-jammy
  template: kubernetes
  var-files: common,kvm,linux,ubuntu-jammy,kubernetes,kubernetes_1_25
  path-filters: |
    paths:
      - .github/workflows/pr.yml
      - bin/*
      - config.pkr.hcl
      - requirements.yml
      - env/*/common.env
      - env/*/kvm.env
      - env/*/linux.env
      - env/*/ubuntu-jammy.env
      - env/*/kubernetes.env
      - env/*/kubernetes_1_25.env
      - vars/*/common.json
      - vars/*/kvm.json
      - vars/*/linux.json
      - vars/*/ubuntu-jammy.json
      - vars/*/kubernetes.json
      - vars/*/kubernetes_1_25.json
      - packer/kubernetes.pkr.hcl
      - vendor/image-builder/**

- name: kubernetes-1-26-focal
  template: kubernetes
  var-files: common,kvm,linux,ubuntu-focal,kubernetes,kubernetes_1_26
  path-filters: |
    paths:
      - .github/workflows/pr.yml
      - bin/*
      - config.pkr.hcl
      - requirements.yml
      - env/*/common.env
      - env/*/kvm.env
      - env/*/linux.env
      - env/*/ubuntu-focal.env
      - env/*/kubernetes.env
      - env/*/kubernetes_1_26.env
      - vars/*/common.json
      - vars/*/kvm.json
      - vars/*/linux.json
      - vars/*/ubuntu-focal.json
      - vars/*/kubernetes.json
      - vars/*/kubernetes_1_26.json
      - packer/kubernetes.pkr.hcl
      - vendor/image-builder/**

- name: kubernetes-1-26-jammy
  template: kubernetes
  var-files: common,kvm,linux,ubuntu-jammy,kubernetes,kubernetes_1_26
  path-filters: |
    paths:
      - .github/workflows/pr.yml
      - bin/*
      - config.pkr.hcl
      - requirements.yml
      - env/*/common.env
      - env/*/kvm.env
      - env/*/linux.env
      - env/*/ubuntu-jammy.env
      - env/*/kubernetes.env
      - env/*/kubernetes_1_26.env
      - vars/*/common.json
      - vars/*/kvm.json
      - vars/*/linux.json
      - vars/*/ubuntu-jammy.json
      - vars/*/kubernetes.json
      - vars/*/kubernetes_1_26.json
      - packer/kubernetes.pkr.hcl
      - vendor/image-builder/**

- name: kubernetes-1-27-focal
  template: kubernetes
  var-files: common,kvm,linux,ubuntu-focal,kubernetes,kubernetes_1_27
  path-filters: |
    paths:
      - .github/workflows/pr.yml
      - bin/*
      - config.pkr.hcl
      - requirements.yml
      - env/*/common.env
      - env/*/kvm.env
      - env/*/linux.env
      - env/*/ubuntu-focal.env
      - env/*/kubernetes.env
      - env/*/kubernetes_1_27.env
      - vars/*/common.json
      - vars/*/kvm.json
      - vars/*/linux.json
      - vars/*/ubuntu-focal.json
      - vars/*/kubernetes.json
      - vars/*/kubernetes_1_27.json
      - packer/kubernetes.pkr.hcl
      - vendor/image-builder/**

- name: kubernetes-1-27-jammy
  template: kubernetes
  var-files: common,kvm,linux,ubuntu-jammy,kubernetes,kubernetes_1_27
  path-filters: |
    paths:
      - .github/workflows/pr.yml
      - bin/*
      - config.pkr.hcl
      - requirements.yml
      - env/*/common.env
      - env/*/kvm.env
      - env/*/linux.env
      - env/*/ubuntu-jammy.env
      - env/*/kubernetes.env
      - env/*/kubernetes_1_27.env
      - vars/*/common.json
      - vars/*/kvm.json
      - vars/*/linux.json
      - vars/*/ubuntu-jammy.json
      - vars/*/kubernetes.json
      - vars/*/kubernetes_1_27.json
      - packer/kubernetes.pkr.hcl
      - vendor/image-builder/**

- name: kubernetes-1-28-focal
  template: kubernetes
  var-files: common,kvm,linux,ubuntu-focal,kubernetes,kubernetes_1_28
  path-filters: |
    paths:
      - .github/workflows/pr.yml
      - bin/*
      - config.pkr.hcl
      - requirements.yml
      - env/*/common.env
      - env/*/kvm.env
      - env/*/linux.env
      - env/*/ubuntu-focal.env
      - env/*/kubernetes.env
      - env/*/kubernetes_1_28.env
      - vars/*/common.json
      - vars/*/kvm.json
      - vars/*/linux.json
      - vars/*/ubuntu-focal.json
      - vars/*/kubernetes.json
      - vars/*/kubernetes_1_28.json
      - packer/kubernetes.pkr.hcl
      - vendor/image-builder/**

- name: kubernetes-1-28-jammy
  template: kubernetes
  var-files: common,kvm,linux,ubuntu-jammy,kubernetes,kubernetes_1_28
  path-filters: |
    paths:
      - .github/workflows/pr.yml
      - bin/*
      - config.pkr.hcl
      - requirements.yml
      - env/*/common.env
      - env/*/kvm.env
      - env/*/linux.env
      - env/*/ubuntu-jammy.env
      - env/*/kubernetes.env
      - env/*/kubernetes_1_28.env
      - vars/*/common.json
      - vars/*/kvm.json
      - vars/*/linux.json
      - vars/*/ubuntu-jammy.json
      - vars/*/kubernetes.json
      - vars/*/kubernetes_1_28.json
      - packer/kubernetes.pkr.hcl
      - vendor/image-builder/**
