---
#####
# This file defines the builds that will be executed by the CI
#####

- name: ubuntu-desktop
  template: linux-desktop
  var-files: common,kvm,linux,ubuntu-noble

- name: jupyter-repo2docker
  template: jupyter-repo2docker
  var-files: common,kvm,linux,ubuntu-noble

- name: linux-rstudio
  template: linux-rstudio
  var-files: common,kvm,linux,ubuntu-noble

- name: kubernetes-1-30-noble
  template: kubernetes
  var-files: common,kvm,linux,ubuntu-noble,kubernetes,kubernetes_1_30

- name: kubernetes-1-31-noble
  template: kubernetes
  var-files: common,kvm,linux,ubuntu-noble,kubernetes,kubernetes_1_31

- name: kubernetes-1-32-noble
  template: kubernetes
  var-files: common,kvm,linux,ubuntu-noble,kubernetes,kubernetes_1_32

- name: kubernetes-1-33-noble
  template: kubernetes
  var-files: common,kvm,linux,ubuntu-noble,kubernetes,kubernetes_1_33
