---
- name: Ensure ansible-init directories exist
  ansible.builtin.file:
    path: "/etc/ansible-init/{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
    - includes
    - playbooks
    - vars

- name: Install task includes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/ansible-init/includes/{{ item }}
    mode: "0644"
    owner: root
    group: root
  loop:
    - data-volumes-configure-volume.yml

- name: Install ansible-init vars for volumes
  ansible.builtin.copy:
    content: "{{ {'data_volumes': data_volumes} | to_nice_yaml }}"
    dest: /etc/ansible-init/vars/data-volumes.yml
    mode: "0644"
    owner: root
    group: root

- name: Install ansible-init playbook
  ansible.builtin.copy:
    src: data-volumes-playbook.yml
    # Leave some numbers for playbooks to execute before
    dest: /etc/ansible-init/playbooks/10-data-volumes.yml
    mode: "0644"
    owner: root
    group: root
