---

- name: Ensure ansible-init directories exist
  file:
    path: "/etc/ansible-init/{{ item }}"
    state: directory
  loop:
    - includes
    - playbooks
    - vars

- name: Install task includes
  copy:
    src: "{{ item }}"
    dest: /etc/ansible-init/includes/{{ item }}
  loop:
    - data-volumes-configure-volume.yml

- name: Install ansible-init vars for volumes
  copy:
    content: "{{ { 'data_volumes': data_volumes } | to_nice_yaml }}"
    dest: /etc/ansible-init/vars/data-volumes.yml

- name: Install ansible-init playbook
  copy:
    src: data-volumes-playbook.yml
    # Leave some numbers for playbooks to execute before
    dest: /etc/ansible-init/playbooks/10-data-volumes.yml
