---

- include_role: 
    name: linux-podman
    tasks_from: install.yml

- include_role:
    name: linux-data-volumes
  vars:
    data_volumes:
      - metadata_var: zenith_volume_id
        mountpoint: /etc/zenith/ssh
        opts: "defaults,nofail"
        owner: podman
        group: podman

- include_role:
    name: linux-guacamole

- name: Install Guacamole ansible-init playbook
  copy:
    src: guacamole-playbook.yml
    # Execute between data volumes and zenith client
    dest: /etc/ansible-init/playbooks/50-guacamole.yml

- include_role:
    name: linux-zenith-client
  vars:
    zenith_client_name: guacamole-zenith-client
    zenith_client_pod: guacamole
    zenith_client_wants: [guacamole-mitm]
    zenith_forward_to_port: 8081
    zenith_registrar_token_metadata_key: zenith_registrar_token_webconsole
    zenith_client_playbook_priority: "51"

- name: Run cloud-init cleanup
  command: cloud-init clean --logs --seed
