---
collections:
  - name: ansible.posix
    version: 2.0.0
  # - name: ansible.windows
  #   version: 1.10.0
  # - name: chocolatey.chocolatey
  #   version: 1.2.0
  - name: community.general
    version: 10.3.0
  # - name: community.windows
  #   version: 1.10.0
  - name: containers.podman
    version: 1.16.3
  - name: prometheus.prometheus
    version: 0.24.1
  - name: https://github.com/azimuth-cloud/ansible-collection-image-utils
    type: git
    version: e2d2620ace588ae8f06fa111f11a3f0e23761cf2

roles:
  - src: https://github.com/stackhpc/ansible-role-os-manila-mount.git
    name: stackhpc.os-manila-mount
    version: v24.5.0
