---
collections:
  - name: ansible.posix
    version: 2.0.0
  # - name: ansible.windows
  #   version: 1.10.0
  # - name: chocolatey.chocolatey
  #   version: 1.2.0
  - name: community.general
    version: 11.2.0
  # - name: community.windows
  #   version: 1.10.0
  - name: containers.podman
    version: 1.17.0
  - name: prometheus.prometheus
    version: 0.27.0
  - name: https://github.com/azimuth-cloud/ansible-collection-image-utils
    type: git
    version: feat/noble

roles:
  - src: https://github.com/stackhpc/ansible-role-os-manila-mount.git
    name: stackhpc.os-manila-mount
    version: v24.5.0
