---
collections:
  - name: ansible.posix
    version: 1.5.4
  # - name: ansible.windows
  #   version: 1.10.0
  # - name: chocolatey.chocolatey
  #   version: 1.2.0
  - name: community.general
    version: 8.5.0
  # - name: community.windows
  #   version: 1.10.0
  - name: containers.podman
    version: 1.12.1
  - name: prometheus.prometheus
    version: 0.16.2

roles:
  - src: https://github.com/stackhpc/ansible-role-os-manila-mount.git
    name: stackhpc.os-manila-mount
    version: v24.1.1
