---
collections:
  - name: ansible.posix
    version: 1.6.2
  # - name: ansible.windows
  #   version: 1.10.0
  # - name: chocolatey.chocolatey
  #   version: 1.2.0
  - name: community.general
    version: 10.1.0
  # - name: community.windows
  #   version: 1.10.0
  - name: containers.podman
    version: 1.16.2
  - name: prometheus.prometheus
    version: 0.23.0
  - name: https://github.com/azimuth-cloud/ansible-collection-image-utils
    type: git
    version: 0.2.0

roles:
  - src: https://github.com/stackhpc/ansible-role-os-manila-mount.git
    name: stackhpc.os-manila-mount
    version: v24.5.0
