---

- name: Install systemd unit for guacamole pod
  include_role: 
    name: linux-podman
    tasks_from: systemd-unit.yml
  vars:
    podman_service_name: guacamole
    podman_service_type: pod

- name: Pull image for guacamole server
  containers.podman.podman_image:
    name: "{{ guacamole_server_image }}"
  become: yes
  become_user: "{{ podman_service_user }}"

- name: Install systemd unit for guacamole server
  include_role: 
    name: linux-podman
    tasks_from: systemd-unit.yml
  vars:
    podman_service_name: guacamole-server
    podman_service_type: container
    podman_service_image: "{{ guacamole_server_image }}"
    podman_service_pod: guacamole

- name: Ensure guacamole config directory exists
  file:
    path: /etc/guacamole
    state: directory

- name: Pull image for guacamole client
  containers.podman.podman_image:
    name: "{{ guacamole_client_image }}"
  become: yes
  become_user: "{{ podman_service_user }}"

- name: Install systemd unit for guacamole client
  include_role: 
    name: linux-podman
    tasks_from: systemd-unit.yml
  vars:
    podman_service_name: guacamole-client
    podman_service_type: container
    podman_service_image: "{{ guacamole_client_image }}"
    podman_service_pod: guacamole
    # Add a soft dependency on the server
    podman_service_wants:
      - guacamole-server
    podman_service_env:
      GUACAMOLE_HOME: /config
      GUACD_HOSTNAME: localhost
    podman_service_volumes:
      - /etc/guacamole:/config:ro

- name: Ensure guacamole MITM config directory exists
  file:
    path: /etc/guacamole-mitm
    state: directory

- name: Install guacamole MITM config files
  template:
    src: "{{ item }}"
    dest: "/etc/guacamole-mitm/{{ item }}"
  loop:
    - nginx.conf
    - guacamole_auth.js

- name: Pull NGINX image for guacamole MITM
  containers.podman.podman_image:
    name: "{{ guacamole_nginx_image }}"
  become: yes
  become_user: "{{ podman_service_user }}"

- name: Install systemd unit for guacamole MITM
  include_role: 
    name: linux-podman
    tasks_from: systemd-unit.yml
  vars:
    podman_service_name: guacamole-mitm
    podman_service_type: container
    podman_service_image: "{{ guacamole_nginx_image }}"
    podman_service_pod: guacamole
    # Add a soft dependency on the client
    podman_service_wants:
      - guacamole-client
    podman_service_command: >-
      nginx -c /etc/guacamole-mitm/nginx.conf
    podman_service_volumes:
      - /etc/guacamole-mitm:/etc/guacamole-mitm:ro
