---
- name: Ensure Guacamole is configured
  hosts: localhost
  gather_facts: true
  become: true
  vars_files:
    - /etc/ansible-init/vars/guacamole.yml
  vars:
    openstack_metadata: >-
      {{
        (
          lookup(
            'url',
            'http://169.254.169.254/openstack/latest/meta_data.json'
            )| from_json).get(
              'meta', {}
              )
        }}
  tasks:
    - name: Ensure Zenith SSH mount has the correct permissions
      ansible.builtin.file:
        path: "/etc/zenith/ssh"
        state: directory
        owner: "podman"
        group: "podman"
        mode: "0755"

    - name: Write Guacamole user mapping file
      ansible.builtin.copy:
        # yamllint disable rule:line-length
        content: |
          <user-mapping>
              <authorize username="portal" password="portal">
                  <connection name="desktop">
                      <protocol>rdp</protocol>
                      <param name="hostname">{{ openstack_metadata.rdp_host }}</param>
                      <param name="port">3389</param>
                      <param name="username">{{ openstack_metadata.rdp_username }}</param>
                      <param name="password">{{ openstack_metadata.rdp_password }}</param>
                      <param name="ignore-cert">true</param>
                      <param name="enable-wallpaper">true</param>
                  </connection>
              </authorize>
          </user-mapping>
        # yamllint enable rule:line-length
        dest: /etc/guacamole/user-mapping.xml
        owner: "{{ podman_service_user }}"
        group: "{{ podman_service_user }}"
        mode: "0600"

    - name: Start and enable Guacamole services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - guacamole
        - guacamole-server
        - guacamole-client
        - guacamole-mitm
