- name: Enable TurboVNC repo
  ansible.builtin.get_url:
    url: https://turbovnc.org/pmwiki/uploads/Downloads/TurboVNC.repo
    dest: /etc/yum.repos.d/TurboVNC.repo

- name: Install EPEL
  ansible.builtin.dnf:
    name: epel-release

- name: Install VNC-related packages
  ansible.builtin.dnf:
  name:
    - turbovnc
    - nmap-ncat
    - python3

- name: Install Xfce desktop
  ansible.builtin.dnf:
    name: '@Xfce'
  
- name: Install websockify venv
  # Requires separate step so that the upgraded pip is used to install packages
  ansible.builtin.pip:
    name: pip
    virtualenv: /opt/websockify
    virtualenv_command: python3 -m venv
  tags: install

- name: Install websockify package in venv
  ansible.builtin.pip:
    name: websockify
    virtualenv: /opt/websockify
    virtualenv_command: python3 -m venv
  tags: install

- name: Symlink websockify to where Open Ondemand expects
  ansible.builtin.file:
    src: /opt/websockify/bin/websockify
    dest: /opt/websockify/run
    state: link

- name: Disable screensaver # as users might not have passwords
  ansible.builtin.dnf:
    name: xfce4-screensaver
    state: absent
