---
- name: Create temporary directory for CVMFS debs
  ansible.builtin.tempfile:
    state: directory
  register: cvmfs_tempdir

- name: Download CVMFS repo
  ansible.builtin.get_url:
    # yamllint disable-line rule:line-length
    url: https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
    dest: "{{ cvmfs_tempdir.path }}/cvmfs-release-latest_all.deb"
    mode: "0700"
    owner: root
    group: root

- name: Add CVMFS repo
  ansible.builtin.command: "dpkg -i {{ cvmfs_tempdir.path }}/cvmfs-release-latest_all.deb"
  changed_when: true

- name: Install CVMFS
  ansible.builtin.apt:
    name: cvmfs
    update_cache: true

- name: Download EESSI CVMFS config
  ansible.builtin.get_url:
    # yamllint disable-line rule:line-length
    url: https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi_latest_all.deb
    dest: "{{ cvmfs_tempdir.path }}/cvmfs-config-eessi_latest_all.deb"
    mode: "0700"
    owner: root
    group: root

- name: Install EESSI CVMFS config
  ansible.builtin.command: "dpkg -i {{ cvmfs_tempdir.path }}/cvmfs-config-eessi_latest_all.deb"
  changed_when: true

- name: Add base CVMFS config
  community.general.ini_file:
    dest: /etc/cvmfs/default.local
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    section: "null"
    no_extra_spaces: true
    mode: "0644"
    owner: root
    group: root
  loop: "{{ cvmfs_config | dict2items }}"

- name: Ensure CVMFS config is setup
  ansible.builtin.command:
    cmd: "cvmfs_config setup"
  changed_when: true

- name: Clean up temporary directory for CVMFS debs
  ansible.builtin.file:
    path: "{{ cvmfs_tempdir.path }}"
    state: absent
  when: cvmfs_tempdir.path is defined
