---
- name: Download CVMFS repo
  ansible.builtin.get_url:
    url: https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
    dest: '.'

- name: Add CVMFS repo
  shell: 'dpkg -i cvmfs-release-latest_all.deb'

- name: Install CVMFS
  apt:
    name: cvmfs
    update_cache: true

- name: Download EESSI CVMFS config
  ansible.builtin.get_url:
    url: https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi_latest_all.deb
    dest: '.'

- name: Install EESSI CVMFS config
  shell: 'dpkg -i cvmfs-config-eessi_latest_all.deb'

- name: Add base CVMFS config
  community.general.ini_file:
    dest: /etc/cvmfs/default.local
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    section: "null"
    no_extra_spaces: true
  loop: "{{ cvmfs_config | dict2items }}"

- name: Ensure CVMFS config is setup
  command:
    cmd: "cvmfs_config setup"