---

- name: Run prechecks for Monitoring variables
  assert:
    that: "{{ item }} is defined"
    fail_msg: "{{ item }} must be defined"
  loop:
    - prometheus_data_directory

- name: Install systemd unit for monitoring pod
  include_role: 
    name: linux-podman
    tasks_from: systemd-unit.yml
  vars:
    podman_service_name: monitoring
    podman_service_type: pod
    podman_service_wants:
      - user-runtime-dir@1001

- name: Install node_exporter
  import_role:
    name: prometheus.prometheus.node_exporter
    
- include_tasks: grafana.yml

- include_tasks: prometheus.yml

- name: Create vars file for ansible-init
  copy:
    content: "{{ monitoring_init_vars | to_nice_yaml }}"
    dest: /etc/ansible-init/vars/monitoring.yml
  vars:
    monitoring_init_vars:
      prometheus_data: "{{ prometheus_data_directory }}"
      prometheus_podman_user: "{{ podman_service_user }}"
      
- name: Configure monitoring Zenith client
  include_role:
    name: linux-zenith-client
  vars:
    zenith_client_name: monitoring-zenith-client
    zenith_client_pod: monitoring
    zenith_client_wants: [grafana]
    zenith_forward_to_port: "3000"
    zenith_registrar_token_metadata_key: zenith_registrar_token_monitoring
    zenith_client_playbook_priority: "16"

- name: Install monitoring ansible-init playbook
  copy:
    src: monitoring-playbook.yml
    # Execute between data volumes and zenith client
    dest: /etc/ansible-init/playbooks/15-monitoring.yml
