---
- name: Ensure Prometheus config directory exists
  ansible.builtin.file:
    path: /etc/prometheus/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Pull image for Prometheus
  containers.podman.podman_image:
    name: "{{ prometheus_container_image }}:{{ prometheus_version }}"
  become: true
  become_user: "{{ podman_service_user }}"

- name: Install systemd unit for Prometheus
  ansible.builtin.include_role:
    name: linux-podman
    tasks_from: systemd-unit.yml
  vars:
    podman_service_name: "prometheus"
    podman_service_type: container
    podman_service_pod: "monitoring"
    podman_service_wants:
      - node_exporter
    podman_service_image: "{{ prometheus_container_image }}"
    podman_service_volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - "{{ prometheus_data_directory }}:/prometheus:U"
    podman_service_command: |
      --config.file=/etc/prometheus/prometheus.yml \
      --storage.tsdb.path=/prometheus \
      --web.console.libraries=/usr/share/prometheus/console_libraries \
      --web.console.templates=/usr/share/prometheus/consoles \
      --storage.tsdb.retention.size=1GB
