---

- name: Install pip
  ansible.builtin.package:
    name: python3-venv
    state: present

- name: Upgrade pip  # noqa package-latest
  ansible.builtin.pip:
    name: pip
    state: latest
    virtualenv: "{{ repo2docker_venv_path }}"
    virtualenv_command: python3 -m venv

- name: Install repo2docker
  ansible.builtin.pip:
    name:
      # yamllint disable-line rule:line-length
      - "git+https://github.com/jupyterhub/repo2docker.git@{{ repo2docker_version }}"
      - "repo2podman=={{ repo2podman_version }}"
    virtualenv: "{{ repo2docker_venv_path }}"
    virtualenv_command: python3 -m venv

- name: Install systemd unit for repo2docker pod
  ansible.builtin.include_role:
    name: linux-podman
    tasks_from: systemd-unit.yml
  vars:
    podman_service_name: repo2docker
    podman_service_type: pod

- name: Install systemd unit for repo2docker notebook
  ansible.builtin.include_role:
    name: linux-podman
    tasks_from: systemd-unit.yml
  vars:
    podman_service_name: repo2docker-notebook-server
    podman_service_type: container
    podman_service_image: repo2docker-notebook-server
    podman_service_pod: repo2docker
    podman_service_command: |
        jupyter notebook \
        --ip 127.0.0.1 \
        --NotebookApp.token='' \
        --NotebookApp.allow_remote_access=true \
        --NotebookApp.default_url='/lab' \
        --no-browser
    # Mount the data volume into our pod and own it
    podman_service_volumes:
      - "{{ jupyter_data_volume }}:/data:U"

- name: Write repo2docker ansible-init vars file
  ansible.builtin.copy:
    content: "{{ repo2docker_init_vars | to_nice_yaml }}"
    dest: /etc/ansible-init/vars/repo2docker.yml
    mode: "0644"
    owner: root
    group: root
  vars:
    repo2docker_init_vars:
      podman_service_user: "{{ podman_service_user }}"
      jupyter_data_volume: "{{ jupyter_data_volume }}"
      repo2docker_venv_path: "{{ repo2docker_venv_path }}"

- name: Install repo2docker ansible-init playbook
  ansible.builtin.copy:
    src: repo2docker-playbook.yml
    # Execute between data volumes and zenith client
    dest: /etc/ansible-init/playbooks/50-repo2docker.yml
    mode: "0644"
    owner: root
    group: root
