---

- name: Run prechecks for Zenith-client variables
  assert:
    that: "{{ item }} is defined"
    fail_msg: "{{ item }} must be defined"
  loop:
    - zenith_client_name
    - zenith_client_pod
    - zenith_registrar_token_metadata_key
    - zenith_client_playbook_priority
    - zenith_forward_to_port

- name: Ensure Zenith config directory exists
  file:
    path: /etc/zenith/{{ zenith_client_name }}
    state: directory

- name: Pull image for Zenith client
  containers.podman.podman_image:
    name: "{{ zenith_client_image }}"
  become: yes
  become_user: "{{ podman_service_user }}"

- name: Install systemd unit for Zenith client
  include_role:
    name: linux-podman
    tasks_from: systemd-unit.yml
  vars:
    podman_service_name: "{{ zenith_client_name }}"
    podman_service_type: container
    podman_service_pod: "{{ zenith_client_pod }}"
    podman_service_wants: "{{ zenith_client_wants }}"
    podman_service_image: "{{ zenith_client_image }}"
    podman_service_command: "zenith-client connect"
    podman_service_volumes:
      - /etc/zenith/{{ zenith_client_name }}:/etc/zenith:ro
      - /etc/zenith/ssh/{{ zenith_client_name }}:/home/zenith/.ssh:ro

- name: Ensure ansible-init directories exist
  file:
    state: directory
    path: "/etc/ansible-init/{{ item }}"
  loop:
    - vars
    - playbooks
    - includes

- name: Write ansible-init vars file for Zenith client
  copy:
    content: "{{ zenith_client_init_vars | to_nice_yaml }}"
    dest: /etc/ansible-init/vars/{{ zenith_client_name }}.yml
  vars:
    zenith_client_init_vars:
      zenith_client_name: "{{ zenith_client_name }}"
      zenith_client_image: "{{ zenith_client_image }}"
      zenith_forward_to_host: "{{ zenith_forward_to_host }}"
      zenith_forward_to_port: "{{ zenith_forward_to_port }}"
      zenith_registrar_token_metadata_key: "{{ zenith_registrar_token_metadata_key }}"
      zenith_client_config_extra: "{{ zenith_client_config_extra }}"

- name: Install ansible-init playbook for Zenith client
  template:
    src: zenith-playbook.yml
    # Execute between data volumes and zenith client
    dest: /etc/ansible-init/playbooks/{{ zenith_client_playbook_priority }}-{{ zenith_client_name }}.yml
