
---
- name: Install dependencies
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - gpg-agent
      - wget
      - linux-headers-generic
      - linux-image-generic
    state: latest

- name: REMOVEME Try upgrade of all packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://repositories.intel.com/gpu/intel-graphics.key
    state: present

- name: Enable Intel PVC repository
  ansible.builtin.apt_repository:
    repo: "deb https://repositories.intel.com/gpu/ubuntu {{ ansible_distribution_release }}/lts/2350 unified"
    state: present

- name: Install PVC packages
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - linux-headers-generic
      - linux-image-generic
      - flex
      - bison
      - intel-fw-gpu
      - intel-i915-dkms
      - xpu-smi
    state: present

- include_role:
    name: linux-data-volumes
  vars:
    data_volumes:
      - metadata_var: nvme1
        partitions:
          - mountpoint: /mnt/nvme1
            opts: "defaults,nofail"
      - metadata_var: nvme2
        partitions:
          - mountpoint: /mnt/nvme2
            opts: "defaults,nofail"
      - metadata_var: nvme3
        partitions:
          - mountpoint: /mnt/nvme3
            opts: "defaults,nofail"
      - metadata_var: nvme4
        partitions:
          - mountpoint: /mnt/nvme4
            opts: "defaults,nofail"
