---
- name: Ensure common configuration is applied on Linux hosts
  hosts: all
  become: true
  roles:
    - role: linux-common
      vars:
        blacklisted_kernel_modules:
          - nouveau

- name: Install AMD drivers
  hosts: all
  become: true
  tasks:
    - name: Download amdgpu-install package
      ansible.builtin.get_url:
        url: https://repo.radeon.com/amdgpu-install/7.0.2/ubuntu/jammy/amdgpu-install_7.0.2.70002-1_all.deb
        dest: "/tmp/amdgpu-install_7.0.2.70002-1_all.deb"
        mode: "0644"

    - name: Install amdgpu-install package
      ansible.builtin.apt:
        deb: "/tmp/amdgpu-install_7.0.2.70002-1_all.deb"
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Install kernel headers and modules
      ansible.builtin.apt:
        update_cache: true
        name:
          - "linux-headers-{{ ansible_kernel }}"
          - "linux-modules-extra-{{ ansible_kernel }}"
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive
        NEEDRESTART_MODE: a
        NEEDRESTART_SUSPEND: "1"

    - name: Install amdgpu-dkms
      ansible.builtin.shell:
        cmd: apt-get install -y amdgpu-dkms > /var/log/amdgpu-dkms-install.log 2>&1 # noqa command-instead-of-module
      environment:
        DEBIAN_FRONTEND: noninteractive
      changed_when: true

    - name: Load amdgpu module
      community.general.modprobe:
        name: amdgpu
        state: present

- name: Import CAPI image playbook
  import_playbook: ../vendor/image-builder/images/capi/ansible/node.yml
