---
- name: Ensure common configuration is applied on Linux hosts
  hosts: all
  become: true
  roles:
    - role: linux-common
      vars:
        blacklisted_kernel_modules:
          - nouveau

- name: Import CAPI image playbook
  import_playbook: ../vendor/image-builder/images/capi/ansible/node.yml
