---
- name: Ensure common configuration is applied on Linux hosts
  hosts: all
  become: true
  roles:
    - role: linux-common
      vars:
        blacklisted_kernel_modules:
          - nouveau

- name: Install AMDGPU drivers
  hosts: all
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  roles:
    - role: ../vendor/image-builder/images/capi/ansible/roles/gpu
      vars:
        gpu_vendor: "amd"
        amd_version: "7.0.2"
        amd_deb_version: "7.0.2.70002-1"
        gpu_amd_usecase: "dkms"

- name: Import CAPI image playbook
  import_playbook: ../vendor/image-builder/images/capi/ansible/node.yml
