---

- hosts: all
  become: yes
  vars:
    enable_pvc: true
    configure_nvme: true
  roles:
    - role: linux-common
      vars:
        blacklisted_kernel_modules:
          - nouveau

- import_playbook: ../vendor/image-builder/images/capi/ansible/node.yml
