- hosts: localhost
  gather_facts: true
  become: true
  vars:
    os_metadata: "{{ lookup('url', 'http://169.254.169.254/openstack/latest/meta_data.json') | from_json }}"
    os_user_metadata: "{{ os_metadata.get('meta', {}) }}"
    os_project_id: "{{ os_metadata.project_id }}"
  tasks:
  - name: Ensure Zenith SSH mount has the correct permissions
    file:
      path: "/etc/zenith/ssh"
      state: directory
      owner: "podman"
      group: "podman"
      mode: '0755'

  - name: Ensure data mount has the correct permissions
    file:
      path: "/data"
      state: directory
      owner: "podman"
      group: "podman"
      mode: '0755'

  - name: Ensure rstudio-server service is enabled and started
    service:
      name: rstudio-server
      state: started
      enabled: yes

  - name: Ensure symbolic link to data volume exists in rstudio home dir
    ansible.builtin.file:
      src: /data
      dest: /home/rstudio/data
      owner: rstudio
      group: rstudio
      state: link