---
- name: "Install systemd unit for {{ podman_service_name }}"
  ansible.builtin.template:
    src: systemd.{{ podman_service_type }}.service.j2
    dest: /etc/systemd/system/{{ podman_service_name }}.service
    owner: root
    group: root
    mode: "0644"
