---
name: Build and test main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  # Build, publish and test the images
  build_test_images:
    uses: ./.github/workflows/build_test_images.yaml
    secrets: inherit
