---
name: Build and test PR

permissions:
  contents: read
  packages: write
  # To report GitHub Actions status checks
  statuses: write
  security-events: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          submodules: true

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.4.0

      - name: Load super-linter configuration
        # Use grep inverse matching to exclude eventual comments in the .env file
        # because the GitHub Actions command to set environment variables doesn't
        # support comments.
        # Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable
        run: grep -v '^#' super-linter.env >> "$GITHUB_ENV"

      - name: Run super-linter
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # This job exists so that PRs from outside the main repo are rejected
  fail_on_remote:
    runs-on: ubuntu-latest
    steps:
      - name: PR must be from a branch in the azimuth-cloud/azimuth-images repo
        run: | 
          if [ "${{ github.repository }}" != "azimuth-cloud/azimuth-images" ]; then
            exit 1
          fi

  # Build, publish and test the images
  build_test_images:
    needs:
      - fail_on_remote
      - lint
    # Don't build draft PRs
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/build_test_images.yaml
    secrets: inherit

  # Purge the manifest and images that we just tested from S3
  purge_images:
    needs:
      - build_test_images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install s3cmd
        run: |
          sudo apt-get update -y
          sudo apt-get install -y s3cmd

      - name: Purge tested images from S3
        run: ./bin/purge-manifest "${GITHUB_SHA}.manifest"
        env:
          S3_HOST: ${{ vars.S3_HOST }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
