---
name: Purge defunct images

permissions:
  contents: read

on:  # yamllint disable-line rule:truthy
  # Allow manual executions
  workflow_dispatch:
  # Run nightly
  schedule:
    - cron: "0 6 * * *"

jobs:
  purge_defunct_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Wait if other workflows are in_progress
        run: |
          # Filter out our run_id, then jq exits 0 if there are
          # other runs in progress, and 4 if it receives an empty
          # list. Sleep while jq is exiting 0 because there are
          # in_progress jobs, and leave this step when there are
          # none
          while gh run list --json name,status,startedAt,headBranch,databaseId --status in_progress |\
                     jq -e -r ".[] | select(.databaseId != ${RUN_ID})"; do
            sleep 60
          done
        env:
          GH_TOKEN: ${{ github.token }}
          RUN_ID: ${{ github.run_id }}

      - name: Install uv
        uses: astral-sh/setup-uv@eb1897b8dc4b5d5bfe39a428a8f2304605e0983c # v7.0.0

      - name: Install script dependencies
        run: |
          uv sync --locked
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"

      - name: Run script to purge defunct images
        run: ./bin/purge-defunct
        env:
          S3_HOST: ${{ vars.CLOUDFLARE_S3_HOST }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          S3_ACCESS_KEY: ${{ secrets.CLOUDFLARE_S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.CLOUDFLARE_S3_SECRET_KEY }}
