---
name: Python script tests

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - "bin/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/python-tests.yml"
  push:
    branches:
      - main
    paths:
      - "bin/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/python-tests.yml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup UV
        uses: astral-sh/setup-uv@eb1897b8dc4b5d5bfe39a428a8f2304605e0983c # v7.0.0

      - name: Install script dependencies
        run: uv sync --locked

      - name: Run pytest
        run: uv run pytest

      - name: Run mypy
        run: uv run mypy
