---
- name: Configure Podman
  ansible.builtin.include_role:
    name: linux-podman
    tasks_from: install.yml

- name: Congfigure data volumes
  ansible.builtin.include_role:
    name: linux-data-volumes
  vars:
    data_volumes:
      - metadata_var: zenith_volume_id
        mountpoint: /etc/zenith/ssh
        opts: "defaults,nofail"
      - metadata_var: data_volume_id
        mountpoint: /data
        opts: "defaults,nofail"

- name: Configure RStudio
  ansible.builtin.include_tasks: rstudio.yml

- name: Install rstudio ansible-init playbook
  ansible.builtin.copy:
    src: rstudio-server-playbook.yml
    # Execute between data volumes and zenith client
    dest: /etc/ansible-init/playbooks/50-rstudio.yml
    owner: root
    group: root
    mode: "0755"

- name: Configure monitoring services
  ansible.builtin.include_role:
    name: linux-monitoring
  vars:
    prometheus_data_directory: /data/prometheus/database

- name: Install systemd unit for rstudio pod
  ansible.builtin.include_role:
    name: linux-podman
    tasks_from: systemd-unit.yml
  vars:
    podman_service_name: rstudio
    podman_service_type: pod

- name: Configure Zenith client
  ansible.builtin.include_role:
    name: linux-zenith-client
  vars:
    zenith_client_name: rstudio-zenith-client
    # The deb install of rstudio-server creates a systemd unit for us
    zenith_client_needs:
      - rstudio-server
    zenith_client_pod: rstudio
    zenith_forward_to_host: "HOST_IP"
    zenith_forward_to_port: 8787
    zenith_registrar_token_metadata_key: zenith_registrar_token_rstudio
    zenith_client_playbook_priority: "51"

- name: Run cloud-init cleanup
  ansible.builtin.command: cloud-init clean --logs --seed
  changed_when: true
