---

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure up-to-date CA certificates
  package:
    name: ca-certificates
    state: latest

# Required for become to an unprivileged user to work
# Using the apt module seems to work more reliably than package :-/
- name: Install ACL package
  apt:
    update_cache: yes
    name: acl
    state: present
  when: ansible_os_family == "Debian"

- include_role:
    name: azimuth_cloud.image_utils.linux_ansible_init

- include_role: 
    name: linux-podman
    tasks_from: install.yml

- include_role:
    name: linux-data-volumes
  vars:
    data_volumes:
      - metadata_var: zenith_volume_id
        mountpoint: /etc/zenith/ssh
        opts: "defaults,nofail"
        owner: podman
        group: podman
      - metadata_var: data_volume_id
        mountpoint: /data
        opts: "defaults,nofail"
        owner: podman
        group: podman

- include_tasks: rstudio.yml

- name: Install rstudio ansible-init playbook
  copy:
    src: rstudio-server-playbook.yml
    # Execute between data volumes and zenith client
    dest: /etc/ansible-init/playbooks/50-rstudio.yml

- include_role:
    name: linux-monitoring
  vars:
    prometheus_data_directory: /data/prometheus/database

- name: Install systemd unit for rstudio pod
  include_role: 
    name: linux-podman
    tasks_from: systemd-unit.yml
  vars:
    podman_service_name: rstudio
    podman_service_type: pod

- include_role:
    name: linux-zenith-client
  vars:
    zenith_client_name: rstudio-zenith-client
    # The deb install of rstudio-server creates a systemd unit for us
    zenith_client_wants: [rstudio-server]
    zenith_client_pod: rstudio
    zenith_forward_to_host: "HOST_IP"
    zenith_forward_to_port: 8787
    zenith_registrar_token_metadata_key: zenith_registrar_token_rstudio
    zenith_client_playbook_priority: "51"

- name: Run cloud-init cleanup
  command: cloud-init clean --logs --seed
