---

- include_role: 
    name: linux-podman
    tasks_from: install.yml

- include_role:
    name: linux-data-volumes
  vars:
    data_volumes:
      - metadata_var: zenith_volume_id
        mountpoint: /etc/zenith/ssh
        opts: "defaults,nofail"
      - metadata_var: data_volume_id
        mountpoint: /data
        opts: "defaults,nofail"

- include_tasks: rstudio.yml

- name: Install rstudio ansible-init playbook
  copy:
    src: rstudio-server-playbook.yml
    # Execute between data volumes and zenith client
    dest: /etc/ansible-init/playbooks/50-rstudio.yml

- include_role:
    name: linux-monitoring
  vars:
    prometheus_data_directory: /data/prometheus/database

- name: Install systemd unit for rstudio pod
  include_role: 
    name: linux-podman
    tasks_from: systemd-unit.yml
  vars:
    podman_service_name: rstudio
    podman_service_type: pod

- include_role:
    name: linux-zenith-client
  vars:
    zenith_client_name: rstudio-zenith-client
    # The deb install of rstudio-server creates a systemd unit for us
    zenith_client_wants: [rstudio-server]
    zenith_client_pod: rstudio
    zenith_forward_to_host: "HOST_IP"
    zenith_forward_to_port: 8787
    zenith_registrar_token_metadata_key: zenith_registrar_token_rstudio
    zenith_client_playbook_priority: "51"

- name: Run cloud-init cleanup
  command: cloud-init clean --logs --seed
